export const userRegistrationTemplate = {
  ItemId: "f9759e1e-30fe-4e3d-a74d-d3298bda4f8b",
  MailPurpose: "AccountActivation",
  PersonaEnabled: false,
  Password: "1234ABcd!!",
  UserName: "testuser",
  Email: "testuser@yopmail.com",
  DisplayName: "Test_User",
  PhoneNumber: "+8801686799541",
  ProfileImageUrl: "",
  SignUp: true,
  DefaultPassword: "",
  RegisteredBy: 1,
  Roles: ["appuser"],
  CountryCode: "BD",
  TwoFactorEnabled: false,
  FirstName: "Test",
  LastName: "User",
  Salutation: "Sir",
  Language: "en-US",
  HostDomain: "misterloo.seliselocal.com",
  AutoExpire: false,
  ExpireOn: "2024-09-20T06:59:50.794Z",
  TwoFactorAuthType: "sms",
};
